server:
  port: 19998

spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: localhost:9200
      cluster: hugo-es
      index: zipkin
      index-shards: 1
      index-replicas: 0


logging:
  file: D:/ky_work/micro-service/log/${spring.application.name}
  level:
    ROOT: INFO
    com.ms: INFO
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN
