server:
  port: 18002

info:
  component: Config Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:eureka.ms.com}:${eureka.server.port:18001}/eureka/

spring:
  profiles:
    active: native #本地文件
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config  #本地文件访问路径 也可以指定磁盘路径，如：search-locations: file:D:/ky_work/conf-file
      enabled: true


#spring:
#  zipkin:
#    baseUrl: trubine.ms.com
#  sleuth:
#    sampler:
#      percentage: 1.0

#spring.rabbitmq:
#  host: mq.ms.com
#  port: 5672
#  username: admin
#  password: admin

logging:
  file: D:/ky_work/micro-service/log/${spring.application.name}
  level:
    ROOT: INFO
    com.ms: INFO
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN
