server:
  port: 8060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/hugo?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: xxxxxx
    password: xxxxxx
  profiles:
    active: test
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 11
    timeout: 30000
    pool:
      max-active: 20
      max-idle: 5

logging:
  file: ${spring.application.name}
  level:
    ROOT: info
    org.springframework: info
    org.springframework.web.servlet.view: info
    org.springframework.web.servlet.mvc: info
    io.undertow.request: info
    org.mybatis: debug
    com.github.pagehelper: TRACE
    com.zaxxer.hikari: TRACE
ribbon.ReadTimeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:eureka.ms.com}:${eureka.server.port:18001}/eureka/